// Seed data — fictional households for prototype demo
// NOTE: all names are placeholders, not real people

const TEAM = [
  { id: 'tm1', name: 'David Reed',     initials: 'DR', role: 'Team Lead',  color: '#3b82f6' },
  { id: 'tm2', name: 'Sarah Pike',     initials: 'SP', role: 'Treasurer',  color: '#10b981' },
  { id: 'tm3', name: 'Marcus Hall',    initials: 'MH', role: 'Member',     color: '#f59e0b' },
  { id: 'tm4', name: 'Anna Beckett',   initials: 'AB', role: 'Member',     color: '#8b5cf6' },
  { id: 'tm5', name: 'Tom Whitfield',  initials: 'TW', role: 'Member',     color: '#ef4444' },
  { id: 'tm6', name: 'Grace Lin',      initials: 'GL', role: 'Member',     color: '#06b6d4' },
  { id: 'tm7', name: 'Paul Mendez',    initials: 'PM', role: 'Member',     color: '#84cc16' },
  { id: 'tm8', name: 'Rachel Owens',   initials: 'RO', role: 'Member',     color: '#ec4899' },
  { id: 'tm9', name: 'Ben Carver',     initials: 'BC', role: 'Member',     color: '#6366f1' },
];
const ME_ID = 'tm4'; // logged-in user

// Households — fictional surname + members. case # is the public ID.
const CASES = [
  {
    id: 'c1', caseNumber: 'B-2026-014',
    household: 'Alvarez',
    members: [
      { name: 'Maria Alvarez',   role: 'Head of household', age: 38 },
      { name: 'Carlos Alvarez',  role: 'Spouse',            age: 41 },
      { name: 'Sofia Alvarez',   role: 'Child',             age: 9 },
      { name: 'Diego Alvarez',   role: 'Child',             age: 6 },
    ],
    type: 'rent',
    status: 'active',
    assigned: ['tm4', 'tm6'],
    opened: '2026-05-08',
    lastActivity: '2026-05-20T14:22:00',
    amounts: { requested: 1850, approved: 1850, disbursed: 0 },
    summary: 'Behind on May rent after Carlos was laid off from his warehouse job April 28. Landlord has begun eviction notice. Maria works part-time at the school cafeteria.',
    notes: [
      { id: 'n1', author: 'tm4', date: '2026-05-20T14:22:00', channel: 'visit',
        text: "Met at their apartment. Carlos has two job interviews lined up next week — Amazon warehouse and a roofing crew. Maria's mom is helping with childcare. Landlord agreed to wait until May 31 if we can cover this month's rent ($1,850)." },
      { id: 'n2', author: 'tm6', date: '2026-05-15T19:10:00', channel: 'call',
        text: "Talked w/ Maria. She's anxious but composed. Grocery situation OK for now — she got food box from Westside Pantry last Saturday. Main worry is rent + electric. Asked about getting Carlos connected to PCA Job Network." },
      { id: 'n3', author: 'tm1', date: '2026-05-10T09:00:00', channel: 'general',
        text: "Pastor Mike referred this family after Sunday service. Carlos has been a member 6 yrs, baptized 2022. Reached out to Anna & Grace to take lead." },
    ],
    files: [
      { id: 'f1', name: 'May-rent-notice.pdf',     size: '184 KB', uploadedBy: 'tm4', date: '2026-05-20' },
      { id: 'f2', name: 'lease-agreement.pdf',     size: '1.2 MB', uploadedBy: 'tm4', date: '2026-05-18' },
      { id: 'f3', name: 'electric-bill-april.pdf', size: '92 KB',  uploadedBy: 'tm6', date: '2026-05-15' },
    ],
    requests: [
      { id: 'r1', amount: 1850, purpose: 'May rent — to landlord directly',
        requester: 'tm4', date: '2026-05-15T20:00:00', status: 'approved',
        votes: [{ tm: 'tm1', vote: 'yes', at: '2026-05-15T20:14' },
                { tm: 'tm2', vote: 'yes', at: '2026-05-15T20:31' },
                { tm: 'tm3', vote: 'yes', at: '2026-05-16T07:02' },
                { tm: 'tm6', vote: 'yes', at: '2026-05-16T08:15' }],
        path: 'team' /* under $1,500 threshold? this is $1,850 — keep on team path b/c group decided to handle */
      },
    ],
  },
  {
    id: 'c2', caseNumber: 'B-2026-015',
    household: 'Okonkwo',
    members: [
      { name: 'Grace Okonkwo',   role: 'Head of household', age: 54 },
    ],
    type: 'medical',
    status: 'new',
    assigned: ['tm3'],
    opened: '2026-05-19',
    lastActivity: '2026-05-21T08:30:00',
    amounts: { requested: 2400, approved: null, disbursed: 0 },
    summary: 'Out-of-pocket cost for follow-up MRI after early-stage breast cancer diagnosis. Insurance covers most but $2,400 deductible remains.',
    notes: [
      { id: 'n1', author: 'tm3', date: '2026-05-21T08:30:00', channel: 'call',
        text: "Caught up w/ Grace this morning. MRI is scheduled June 4. She has the bill estimate from St. Joseph's. Asked if she'd be OK with us paying the hospital directly — yes, that's her preference." },
      { id: 'n2', author: 'tm3', date: '2026-05-19T18:45:00', channel: 'visit',
        text: "First conversation after small group. Grace shared her diagnosis privately and asked for prayer + help with the deductible. She's currently between contracts (consults for non-profits). Stable housing, no other immediate needs." },
    ],
    files: [
      { id: 'f1', name: 'st-joseph-estimate.pdf', size: '212 KB', uploadedBy: 'tm3', date: '2026-05-20' },
    ],
    requests: [
      { id: 'r1', amount: 2400, purpose: 'MRI deductible — paid directly to St. Joseph\'s Hospital',
        requester: 'tm3', date: '2026-05-20T09:00:00', status: 'deacon_review',
        votes: [{ tm: 'tm1', vote: 'yes', at: '2026-05-20T09:30' },
                { tm: 'tm4', vote: 'yes', at: '2026-05-20T10:15' },
                { tm: 'tm2', vote: 'yes', at: '2026-05-20T11:00' }],
        path: 'deacon',
        meetingDate: '2026-06-02',
      },
    ],
  },
  {
    id: 'c3', caseNumber: 'B-2026-011',
    household: 'Bennett',
    members: [
      { name: 'James Bennett',   role: 'Head of household', age: 67 },
      { name: 'Helen Bennett',   role: 'Spouse',            age: 64 },
    ],
    type: 'utilities',
    status: 'ongoing',
    assigned: ['tm5', 'tm8'],
    opened: '2026-03-12',
    lastActivity: '2026-05-18T16:00:00',
    amounts: { requested: 920, approved: 920, disbursed: 920 },
    summary: 'Fixed-income retirees. Gas + electric arrears built up over winter. We covered Feb-Mar bills directly to provider; checking in monthly.',
    notes: [
      { id: 'n1', author: 'tm5', date: '2026-05-18T16:00:00', channel: 'call',
        text: "Monthly check-in. April bill was manageable. James said the weatherization volunteers from the youth group made a real difference. They're doing OK, no current ask." },
      { id: 'n2', author: 'tm8', date: '2026-04-20T11:00:00', channel: 'visit',
        text: "Dropped off groceries. Helen mentioned she's taking on some online tutoring through PCA Education Network — extra ~$200/mo." },
      { id: 'n3', author: 'tm5', date: '2026-03-15T14:30:00', channel: 'general',
        text: "Paid Duke Energy + Piedmont Gas directly — $612 + $308. Both confirmed." },
    ],
    files: [
      { id: 'f1', name: 'duke-statement-feb.pdf', size: '88 KB', uploadedBy: 'tm5', date: '2026-03-13' },
      { id: 'f2', name: 'piedmont-statement-feb.pdf', size: '76 KB', uploadedBy: 'tm5', date: '2026-03-13' },
    ],
    requests: [],
  },
  {
    id: 'c4', caseNumber: 'B-2026-016',
    household: 'Thornton',
    members: [
      { name: 'Rebecca Thornton', role: 'Head of household', age: 32 },
      { name: 'Owen Thornton',    role: 'Child',             age: 4 },
    ],
    type: 'food',
    status: 'active',
    assigned: ['tm7'],
    opened: '2026-05-14',
    lastActivity: '2026-05-19T12:00:00',
    amounts: { requested: 400, approved: 400, disbursed: 200 },
    summary: 'Single mom recently moved from out-of-state. SNAP application pending. Bridge support for groceries + diapers for 6 weeks while paperwork clears.',
    notes: [
      { id: 'n1', author: 'tm7', date: '2026-05-19T12:00:00', channel: 'text',
        text: "Sent her this week's $100 grocery card. She's caught up on diapers — Owen's now in size 5T pants/pull-ups. SNAP interview scheduled for May 28." },
      { id: 'n2', author: 'tm7', date: '2026-05-14T17:00:00', channel: 'visit',
        text: "Met Rebecca at the cafe near her apartment. Job interview at Target next Tuesday. She's resourceful and motivated, just need to bridge 6 weeks." },
    ],
    files: [],
    requests: [
      { id: 'r1', amount: 400, purpose: 'Bridge grocery cards (4 weeks @ $100)',
        requester: 'tm7', date: '2026-05-14T17:30:00', status: 'approved',
        votes: [{ tm: 'tm1', vote: 'yes', at: '2026-05-14T18:00' },
                { tm: 'tm2', vote: 'yes', at: '2026-05-14T19:14' },
                { tm: 'tm4', vote: 'yes', at: '2026-05-14T19:40' }],
        path: 'team',
      },
    ],
  },
  {
    id: 'c5', caseNumber: 'B-2026-013',
    household: 'Park',
    members: [
      { name: 'Daniel Park',    role: 'Head of household', age: 45 },
      { name: 'Hye-Jin Park',   role: 'Spouse',            age: 43 },
      { name: 'Joshua Park',    role: 'Child',             age: 14 },
    ],
    type: 'transport',
    status: 'pending_team',
    assigned: ['tm9'],
    opened: '2026-05-17',
    lastActivity: '2026-05-20T20:00:00',
    amounts: { requested: 1200, approved: null, disbursed: 0 },
    summary: 'Their only car needs a transmission repair — Daniel uses it for his commute to the hospital where he works night shift as orderly.',
    notes: [
      { id: 'n1', author: 'tm9', date: '2026-05-20T20:00:00', channel: 'call',
        text: "Got the estimate from Brake & Tire on Glenwood — $1,200 for rebuilt transmission, 60-day labor warranty. Daniel says he can pay $200 of it himself if we can cover the rest." },
      { id: 'n2', author: 'tm9', date: '2026-05-17T15:00:00', channel: 'general',
        text: "Daniel called me after worship. Car broke down Friday on the way home from work. He's been getting Uber rides ($45/night) — not sustainable." },
    ],
    files: [
      { id: 'f1', name: 'brake-tire-estimate.jpg', size: '1.4 MB', uploadedBy: 'tm9', date: '2026-05-20' },
    ],
    requests: [
      { id: 'r1', amount: 1000, purpose: 'Transmission repair (family covers $200)',
        requester: 'tm9', date: '2026-05-20T21:00:00', status: 'pending_team',
        votes: [{ tm: 'tm1', vote: 'yes', at: '2026-05-21T07:00' },
                { tm: 'tm4', vote: 'yes', at: '2026-05-21T07:45' }],
        path: 'team',
      },
    ],
  },
  {
    id: 'c6', caseNumber: 'B-2026-010',
    household: 'Williams',
    members: [
      { name: 'Tasha Williams',  role: 'Head of household', age: 29 },
      { name: 'Mia Williams',    role: 'Child',             age: 8 },
      { name: 'Jaylen Williams', role: 'Child',             age: 5 },
    ],
    type: 'childcare',
    status: 'resolved',
    assigned: ['tm6'],
    opened: '2026-02-04',
    lastActivity: '2026-04-30T14:00:00',
    amounts: { requested: 1400, approved: 1400, disbursed: 1400 },
    summary: 'Covered after-school care for 12 weeks while Tasha completed CNA certification. She started full-time at Mercy Hospital April 14.',
    notes: [
      { id: 'n1', author: 'tm6', date: '2026-04-30T14:00:00', channel: 'general',
        text: "Closing case. Tasha is six weeks in at Mercy and stable. She sent a thank-you note for the team — taped on the office fridge :)" },
      { id: 'n2', author: 'tm6', date: '2026-03-20T10:00:00', channel: 'visit',
        text: "Halfway through CNA program, she's at the top of her class. After-school is going smoothly." },
    ],
    files: [],
    requests: [],
  },
  {
    id: 'c7', caseNumber: 'B-2026-009',
    household: 'Khoury',
    members: [
      { name: 'Layla Khoury',    role: 'Head of household', age: 36 },
      { name: 'Sami Khoury',     role: 'Child',             age: 11 },
    ],
    type: 'other',
    status: 'paused',
    assigned: ['tm8'],
    opened: '2026-01-22',
    lastActivity: '2026-04-08T11:00:00',
    amounts: { requested: 600, approved: 600, disbursed: 600 },
    summary: 'Layla declined further help. Connected her with the women\'s ministry support group instead. Paused but case stays open in case she reaches out again.',
    notes: [
      { id: 'n1', author: 'tm8', date: '2026-04-08T11:00:00', channel: 'call',
        text: "Layla is doing better — new job at the library went permanent. She asked us to pause, said she wants to give back when she's able. Sweet conversation." },
    ],
    files: [],
    requests: [],
  },
  {
    id: 'c8', caseNumber: 'B-2026-012',
    household: 'Singh',
    members: [
      { name: 'Arjun Singh',     role: 'Head of household', age: 48 },
      { name: 'Priya Singh',     role: 'Spouse',            age: 46 },
    ],
    type: 'medical',
    status: 'active',
    assigned: ['tm2', 'tm4'],
    opened: '2026-04-30',
    lastActivity: '2026-05-19T09:00:00',
    amounts: { requested: 3200, approved: null, disbursed: 0 },
    summary: 'Priya needs gallbladder surgery, scheduled June 18. Out-of-pocket portion is $3,200. Family has $1,000 saved.',
    notes: [
      { id: 'n1', author: 'tm4', date: '2026-05-19T09:00:00', channel: 'visit',
        text: "Visited at their home. Arjun was apologetic about asking — he's been a deacon at our sister church in Charlotte and feels strange being on this side. Reassured him. Priya in good spirits, just tired." },
      { id: 'n2', author: 'tm2', date: '2026-05-02T13:00:00', channel: 'general',
        text: "Confirmed insurance numbers w/ Priya. $3,200 out-of-pocket is correct after their HSA balance. Hospital will accept payment directly from us." },
    ],
    files: [
      { id: 'f1', name: 'surgery-estimate.pdf', size: '156 KB', uploadedBy: 'tm2', date: '2026-05-02' },
    ],
    requests: [
      { id: 'r1', amount: 2200, purpose: 'Surgery deductible (family pays $1,000 of $3,200)',
        requester: 'tm2', date: '2026-05-19T10:00:00', status: 'deacon_review',
        votes: [{ tm: 'tm1', vote: 'yes', at: '2026-05-19T11:00' },
                { tm: 'tm4', vote: 'yes', at: '2026-05-19T11:15' }],
        path: 'deacon',
        meetingDate: '2026-06-02',
      },
    ],
  },
];

// Audit log — latest actions across the team
const AUDIT = [
  { id: 'a1', at: '2026-05-21T08:30:00', who: 'tm3', action: 'added a note', target: 'B-2026-015', detail: 'Call w/ household' },
  { id: 'a2', at: '2026-05-21T07:45:00', who: 'tm4', action: 'voted yes', target: 'B-2026-013', detail: '$1,000 transmission' },
  { id: 'a3', at: '2026-05-21T07:00:00', who: 'tm1', action: 'voted yes', target: 'B-2026-013', detail: '$1,000 transmission' },
  { id: 'a4', at: '2026-05-20T21:00:00', who: 'tm9', action: 'submitted a request', target: 'B-2026-013', detail: '$1,000' },
  { id: 'a5', at: '2026-05-20T20:00:00', who: 'tm9', action: 'added a note', target: 'B-2026-013', detail: 'Estimate received' },
  { id: 'a6', at: '2026-05-20T14:22:00', who: 'tm4', action: 'added a note', target: 'B-2026-014', detail: 'Home visit' },
  { id: 'a7', at: '2026-05-20T11:00:00', who: 'tm2', action: 'voted yes', target: 'B-2026-015', detail: '$2,400 MRI — deacon path' },
  { id: 'a8', at: '2026-05-20T10:15:00', who: 'tm4', action: 'voted yes', target: 'B-2026-015', detail: '$2,400 MRI — deacon path' },
  { id: 'a9', at: '2026-05-20T09:30:00', who: 'tm1', action: 'voted yes', target: 'B-2026-015', detail: '$2,400 MRI — deacon path' },
  { id: 'a10', at: '2026-05-20T09:00:00', who: 'tm3', action: 'submitted a request', target: 'B-2026-015', detail: '$2,400 — flagged for deacon review' },
  { id: 'a11', at: '2026-05-20T09:00:00', who: 'tm3', action: 'uploaded a file', target: 'B-2026-015', detail: 'st-joseph-estimate.pdf' },
  { id: 'a12', at: '2026-05-19T18:30:00', who: 'tm6', action: 'viewed printable report', target: '—', detail: 'Redacted, for prep' },
  { id: 'a13', at: '2026-05-19T12:00:00', who: 'tm7', action: 'logged a disbursement', target: 'B-2026-016', detail: '$100 grocery card' },
];

const BUDGET = {
  fy: '2026',
  annual: 48000,
  ytdDisbursed: 9420,
  ytdApprovedPending: 4050,
  monthOpened: 3,
  monthResolved: 1,
};

Object.assign(window, { TEAM, ME_ID, CASES, AUDIT, BUDGET });
